2022-12-04 13:55:05,841 INFO    MainThread:1420822 [internal.py:wandb_internal():87] W&B internal server running at pid: 1420822, started at: 2022-12-04 13:55:05.841353
2022-12-04 13:55:05,844 DEBUG   HandlerThread:1420822 [handler.py:handle_request():130] handle_request: run_start
2022-12-04 13:55:05,845 INFO    WriterThread:1420822 [datastore.py:open_for_write():77] open: /homes/vladtom/retweet-prediction-challenge/retweet_prediction_challenge/scripts/wandb/offline-run-20221204_135504-1cudbci8/run-1cudbci8.wandb
2022-12-04 13:55:05,861 DEBUG   HandlerThread:1420822 [meta.py:__init__():40] meta init
2022-12-04 13:55:05,861 DEBUG   HandlerThread:1420822 [meta.py:__init__():54] meta init done
2022-12-04 13:55:05,861 DEBUG   HandlerThread:1420822 [meta.py:probe():214] probe
2022-12-04 13:55:05,868 DEBUG   HandlerThread:1420822 [meta.py:_setup_git():204] setup git
2022-12-04 13:55:05,893 DEBUG   HandlerThread:1420822 [meta.py:_setup_git():211] setup git done
2022-12-04 13:55:05,893 DEBUG   HandlerThread:1420822 [meta.py:_save_pip():58] save pip
2022-12-04 13:55:05,894 DEBUG   HandlerThread:1420822 [meta.py:_save_pip():72] save pip done
2022-12-04 13:55:05,894 DEBUG   HandlerThread:1420822 [meta.py:_save_conda():79] save conda
2022-12-04 13:55:08,697 DEBUG   HandlerThread:1420822 [meta.py:_save_conda():89] save conda done
2022-12-04 13:55:08,698 DEBUG   HandlerThread:1420822 [meta.py:probe():252] probe done
2022-12-04 13:55:42,337 WARNING MainThread:1420822 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-12-04 13:55:42,386 WARNING MainThread:1420822 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-12-04 13:55:42,386 ERROR   MainThread:1420822 [internal.py:wandb_internal():149] Internal process interrupted.
2022-12-04 13:55:42,857 INFO    SenderThread:1420822 [sender.py:finish():1070] shutting down sender
2022-12-04 13:55:43,311 INFO    WriterThread:1420822 [datastore.py:close():281] close: /homes/vladtom/retweet-prediction-challenge/retweet_prediction_challenge/scripts/wandb/offline-run-20221204_135504-1cudbci8/run-1cudbci8.wandb
2022-12-04 13:55:43,313 INFO    MainThread:1420822 [internal.py:handle_exit():77] Internal process exited
